### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by davidemoro**
Readonly fields when you are on the edit form of a translation, support for association_proxy and language independent fields, fixed a random problem due to a missing no_autoflush.

WARNING: no more raise exception when you try to set a language independent field, let's discuss this thing before applying this PR.

### CODE REVIEW

**Comment by disko** [comment]
WOW! Thanks a lot!

I'll move the repository to the Kotti organization and add you as a collaborator, as well as a package maintainer on PyPI if you like (I guess your PyPI username is redomino?) – these changes should make it into a new release, but as have no current multilingual project, you might as well do the release yourself… ;)

**Comment by davidemoro** [comment]
Hi @disko, my PyPI username is no more redomino: that was the older one. I'm going to create a new user.

Thank you ;)

**Comment by davidemoro** [comment]
Hi @disko, here it is my new PyPI username:
davidemoro

**Comment by disko** [comment]
Added you on PyPI.  Happy releasing!  :)

**Comment by davidemoro** [comment]
Hi @disko, I'm going to release on PyPI but I have no push rights on Kotti/kotti_multilingual

**Comment by disko** [comment]
I added you to the team, but forgot to assign the team to the repo.  Should work now.

**Pull request merged**
